(defun func ()    
  (car '( ))
  (cdr '( ))
  ;(car 'x)
  ;(cdr 'x)
  (car '(x))
  (cdr '(x))
  (car '(x y z))
  (cdr '(x y z))
  ;(caar '(x y z))
  (cadr '(x y z))
  ;(cdar '(x y z))
  (cddr '(x y z))
  (caar '((x y z)))
  (cadr '((x y z)))
  (cdar '((x y z)))
  (cddr '((x y z)))
  (car '((x y) (z a)))
  (cdr '((z y) (z a)))
  (caar '((x y) (z a)))
  (cadr '((x y) (z a)))
  ;(cdar '((x y) (z a)))
  (cddr '((x y) (z a)))
  (car '(( ) ((x y))))
  (cdr '(( ) ((x y))))
  )
